TESTS := test-config test-controls test-dispatcher test-layering        \
         test-messages test-mode-mgr test-note-mgr test-param           \
         test-parser test-timbre-mgr

include ../../make/common.make
