PROGRAMS := simple-beep

CPPFLAGS := -DPLATFORM_CONFIG_H='"platforms/macos/config.h"'
CPPFLAGS += -DTARGET_CONFIG_H='"targets/simple-beep/config.h"'
simple-beep-SOURCES := simple-beep.cpp ../../synth/core/planner.cpp

include ../../make/common.make
