PROGRAMS := simple-beep

CPPFLAGS := -DPLATFORM_SIZES_H='"platforms/macos/sizes.h"'
CPPFLAGS += -DTARGET_SIZES_H='"targets/simple-beep/sizes.h"'
simple-beep-SOURCES := simple-beep.cpp ../../synth/core/planner.cpp

include ../../make/common.make
