                    TESTS := test-actions test-mod-network test-plan test-voice
                 PROGRAMS := a.out example
 test-mod-network-SOURCES := mod-network.cpp
            a.out-SOURCES := main.cpp
          example-SOURCES := example.cpp
              TARGET_ARCH := -march=skylake-avx512

include ../../make/common.make
