       TESTS := test-action test-controls test-link test-modules        \
                test-patch test-plan test-planner test-ported           \
                test-ports test-resolver test-steps test-synth          \
                test-timbre test-voice

    PROGRAMS := a.out example
 TARGET_ARCH := -march=native

 test-planner-SOURCES := planner.cpp
   test-synth-SOURCES := planner.cpp
        a.out-SOURCES := main.cpp
      example-SOURCES := example.cpp

include ../../make/common.make
