       TESTS := test-actions test-controls test-links			\
                test-mod-network test-mod-vector test-modules		\
                test-plan test-ported test-ports test-resolver		\
                test-timbre test-voice
    PROGRAMS := a.out example
 TARGET_ARCH := -march=native

 test-mod-network-SOURCES := mod-network.cpp
            a.out-SOURCES := main.cpp
          example-SOURCES := example.cpp

include ../../make/common.make
